### ISSUE TITLE
devel biocVersion not installable on R-devel just before next R release

### ISSUE THREAD

**Issue by sneumann** [Bioconductor/BiocVersion#1]
Hi,
in the weeks before releasing the next R release, biocVersion in BioC-devel is not installable,
because it is tied to an exact range of R versions `R (>= 3.6.0), R (< 3.7.0)` resulting in 
```
ok <- BiocManager::install(pkgs_to_install, update=FALSE, ask=FALSE) %in% rownames(installed.packages())
Bioconductor version 3.9 (BiocManager 1.30.4), R Under development (unstable)
(2019-03-30 r76304)
Installing package(s) 'BiocVersion', 'biocViews', 'ProtGenerics', 'mzR',
...
	‘/tmp/RtmpvBEE7T/downloaded_packages’
Warning messages:
1: package ‘BiocVersion’ is not available (for R Under development) 
```
There is no code workaround available, as the R version check is beyond 
the reach of `BiocManager`.

If `biocVersion` sticks to the policy of allowing one and only one major R release,
`BiocManager` needs access to a `biocVersion` already matching the "future" R.

Alternatively, `biocVersion` **in Bioc-devel** could relax the version requirement 
to also allow installation on *one* future R version:
`R (>= 3.6.0), R (<= 3.7.0)` which in the `RELEASE_3_9` branch would then get 
reverted to `R (>= 3.6.0), R (< 3.7.0)`. 

Note that this issue only appears in the spring BioC release, which interleaves 
with the R release. Autumn BioC releases should be fine.

Yours, Steffen

**Comment by LiNk-NY** [comment]
Hi Steffen, @sneumann 

It appears that your version of R devel is too ahead of what `BiocVersion` allows. 
This is due to version updates on CRAN and recent changes to `BiocVersion` in
preparation for the release. 

Please use the 'beta' version of R release which should fit the desired intervals that
`BiocVersion` specifies. This should be stable through the next R and Bioc releases. 

Best, 
Marcel

**Comment by sneumann** [comment]
Hi, 
thanks for chiming in. Indeed, my R is too new. 
This issue is triggered by https://github.com/Bioconductor/bioc_docker/issues/79 
@lshep got the answer from the rocker guys that we'll have to live with their versions. 
So changing R versions in the `bioconductor/devel_*` images is not an option.

I had created a hack https://github.com/Bioconductor/bioc_docker/pull/83 
that would allow `BiocVersion` to be installed in this case, but the suggestion was 
to find something that could work even outside the `bioconductor/devel_*` images.
So the question remains what are we going to do about `biocVersion` in the months of April.

Yours, Steffen

**Comment by LiNk-NY** [comment]
Hi Steffen, @sneumann 

I see the context of the issue now. 
Yes, this is a problem because we don't have full control of the rocker containers.

We shouldn't use unintended R versions with `BiocVersion` / Bioc releases so to me,
`R 3.7.0` is off limits. 

Perhaps we can consider using SVN versioning up to a specific checkout or 
impose a specific version of rocker containers. 

I will discuss this with Martin. 

Best, 
Marcel

**Comment by LiNk-NY** [comment]
After a long discussion and arguments from both sides (those for and against using R-devel with Bioc-devel when the version is too new), Martin has implemented this to allow R-devel to be used during the 'summer' release. 
See [c1873aaf74208b93229baa4cbc4c827e3c4c7f02](https://github.com/Bioconductor/BiocManager/commit/c1873aaf74208b93229baa4cbc4c827e3c4c7f02) and https://github.com/Bioconductor/BiocManager/issues/133
